#include "lvgl.h"
#define LV_USE_THEME_MONO 1
#define LV_MEM_SIZE (128U * 1024U)
#define LV_THEME_DEFAULT_INIT lv_theme_mono_init
#define LV_THEME_DEFAULT_COLOR_PRIMARY LV_COLOR_WHITE
#define LV_THEME_DEFAULT_COLOR_SECONDARY LV_COLOR_BLACK
#define LV_THEME_DEFAULT_FLAG 0
#define LV_COLOR_TRANSP LV_COLOR_BLACK
//#define LV_THEME_DEFAULT_INCLUDE <stdint.h>
//#define LV_THEME_DEFAULT_FONT_SMALL &unscii
//#define LV_THEME_DEFAULT_FONT_NORMAL &unscii
//#define LV_THEME_DEFAULT_FONT_SUBTITLE &unscii
//#define LV_THEME_DEFAULT_FONT_TITLE &unscii
